# srs/views_dt.py
# AwardFeedback views for basic operations


#############################################################################
# DO NOT EDIT THIS FILE
# This Code will be replaced by the code generator
#############################################################################

from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.decorators import login_required

from models import AwardFeedback
from awardfeedback import query_awardfeedback, get_awardfeedback


# Basic list view with using a template
class AwardFeedbackList(ListView):
    model = AwardFeedback
    template_name = 'awardfeedback_list.html'

    # Filter the list of choices
    queryset = query_awardfeedback()

    # Use the request user to match the items
    #def get_queryset(self):
    #    return AwardFeedback.objects.filter(name=self.request.user.username)


# Basic detail view
class AwardFeedbackDetail(DetailView):
    model = AwardFeedback
    template_name = 'awardfeedback_detail.html'

    # Call the base implementation first to get a context
    def get_context_data(self, **kwargs):
        context = super(AwardFeedbackDetail, self).get_context_data(**kwargs)
        id = context['object'].pk
        context['value_list'] = get_awardfeedback(self.request.user,id)
        return context


# Create view
class AwardFeedbackAdd(CreateView):
    model = AwardFeedback
    template_name = 'awardfeedback_edit.html'


# Update view
#@login_required(login_url='/login')
class AwardFeedbackEdit(UpdateView):
    model = AwardFeedback
    template_name = 'awardfeedback_edit.html'


# Delete view
class AwardFeedbackDelete(DeleteView):
    model = AwardFeedback
    success_url = reverse_lazy('awardfeedback_list')
    template_name = 'awardfeedback_delete.html'

