# srs/views_dt.py
# Award views for basic operations


#############################################################################
# DO NOT EDIT THIS FILE
# This Code will be replaced by the code generator
#############################################################################

from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.decorators import login_required

from models import Award
from award import query_award, get_award


# Basic list view with using a template
class AwardList(ListView):
    model = Award
    template_name = 'award_list.html'

    # Filter the list of choices
    queryset = query_award()

    # Use the request user to match the items
    #def get_queryset(self):
    #    return Award.objects.filter(name=self.request.user.username)


# Basic detail view
class AwardDetail(DetailView):
    model = Award
    template_name = 'award_detail.html'

    # Call the base implementation first to get a context
    def get_context_data(self, **kwargs):
        context = super(AwardDetail, self).get_context_data(**kwargs)
        id = context['object'].pk
        context['value_list'] = get_award(self.request.user,id)
        return context


# Create view
class AwardAdd(CreateView):
    model = Award
    template_name = 'award_edit.html'


# Update view
#@login_required(login_url='/login')
class AwardEdit(UpdateView):
    model = Award
    template_name = 'award_edit.html'


# Delete view
class AwardDelete(DeleteView):
    model = Award
    success_url = reverse_lazy('award_list')
    template_name = 'award_delete.html'

