# srs/views_dt.py
# Company views for basic operations


#############################################################################
# DO NOT EDIT THIS FILE
# This Code will be replaced by the code generator
#############################################################################

from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.decorators import login_required

from models import Company
from company import query_company, get_company


# Basic list view with using a template
class CompanyList(ListView):
    model = Company
    template_name = 'company_list.html'

    # Filter the list of choices
    queryset = query_company()

    # Use the request user to match the items
    #def get_queryset(self):
    #    return Company.objects.filter(name=self.request.user.username)


# Basic detail view
class CompanyDetail(DetailView):
    model = Company
    template_name = 'company_detail.html'

    # Call the base implementation first to get a context
    def get_context_data(self, **kwargs):
        context = super(CompanyDetail, self).get_context_data(**kwargs)
        id = context['object'].pk
        context['value_list'] = get_company(self.request.user,id)
        return context


# Create view
class CompanyAdd(CreateView):
    model = Company
    template_name = 'company_edit.html'


# Update view
#@login_required(login_url='/login')
class CompanyEdit(UpdateView):
    model = Company
    template_name = 'company_edit.html'


# Delete view
class CompanyDelete(DeleteView):
    model = Company
    success_url = reverse_lazy('company_list')
    template_name = 'company_delete.html'

