# srs/views_dt.py
# Driver views for basic operations


#############################################################################
# DO NOT EDIT THIS FILE
# This Code will be replaced by the code generator
#############################################################################

from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.decorators import login_required

from models import Driver
from driver import query_driver, get_driver


# Basic list view with using a template
class DriverList(ListView):
    model = Driver
    template_name = 'driver_list.html'

    # Filter the list of choices
    queryset = query_driver()

    # Use the request user to match the items
    #def get_queryset(self):
    #    return Driver.objects.filter(name=self.request.user.username)


# Basic detail view
class DriverDetail(DetailView):
    model = Driver
    template_name = 'driver_detail.html'

    # Call the base implementation first to get a context
    def get_context_data(self, **kwargs):
        context = super(DriverDetail, self).get_context_data(**kwargs)
        id = context['object'].pk
        context['value_list'] = get_driver(self.request.user,id)
        return context


# Create view
class DriverAdd(CreateView):
    model = Driver
    template_name = 'driver_edit.html'


# Update view
#@login_required(login_url='/login')
class DriverEdit(UpdateView):
    model = Driver
    template_name = 'driver_edit.html'


# Delete view
class DriverDelete(DeleteView):
    model = Driver
    success_url = reverse_lazy('driver_list')
    template_name = 'driver_delete.html'

