# srs/views_dt.py
# Employee views for basic operations


#############################################################################
# DO NOT EDIT THIS FILE
# This Code will be replaced by the code generator
#############################################################################

from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.decorators import login_required

from models import Employee
from employee import query_employee, get_employee


# Basic list view with using a template
class EmployeeList(ListView):
    model = Employee
    template_name = 'employee_list.html'

    # Filter the list of choices
    queryset = query_employee()

    # Use the request user to match the items
    #def get_queryset(self):
    #    return Employee.objects.filter(name=self.request.user.username)


# Basic detail view
class EmployeeDetail(DetailView):
    model = Employee
    template_name = 'employee_detail.html'

    # Call the base implementation first to get a context
    def get_context_data(self, **kwargs):
        context = super(EmployeeDetail, self).get_context_data(**kwargs)
        id = context['object'].pk
        context['value_list'] = get_employee(self.request.user,id)
        return context


# Create view
class EmployeeAdd(CreateView):
    model = Employee
    template_name = 'employee_edit.html'


# Update view
#@login_required(login_url='/login')
class EmployeeEdit(UpdateView):
    model = Employee
    template_name = 'employee_edit.html'


# Delete view
class EmployeeDelete(DeleteView):
    model = Employee
    success_url = reverse_lazy('employee_list')
    template_name = 'employee_delete.html'

