# srs/views_dt.py
# Group views for basic operations


#############################################################################
# DO NOT EDIT THIS FILE
# This Code will be replaced by the code generator
#############################################################################

from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.decorators import login_required

from models import Group
from group import query_group, get_group


# Basic list view with using a template
class GroupList(ListView):
    model = Group
    template_name = 'group_list.html'

    # Filter the list of choices
    queryset = query_group()

    # Use the request user to match the items
    #def get_queryset(self):
    #    return Group.objects.filter(name=self.request.user.username)


# Basic detail view
class GroupDetail(DetailView):
    model = Group
    template_name = 'group_detail.html'

    # Call the base implementation first to get a context
    def get_context_data(self, **kwargs):
        context = super(GroupDetail, self).get_context_data(**kwargs)
        id = context['object'].pk
        context['value_list'] = get_group(self.request.user,id)
        return context


# Create view
class GroupAdd(CreateView):
    model = Group
    template_name = 'group_edit.html'


# Update view
#@login_required(login_url='/login')
class GroupEdit(UpdateView):
    model = Group
    template_name = 'group_edit.html'


# Delete view
class GroupDelete(DeleteView):
    model = Group
    success_url = reverse_lazy('group_list')
    template_name = 'group_delete.html'

