# srs/views_dt.py
# IdeaFeedback views for basic operations


#############################################################################
# DO NOT EDIT THIS FILE
# This Code will be replaced by the code generator
#############################################################################

from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.decorators import login_required

from models import IdeaFeedback
from ideafeedback import query_ideafeedback, get_ideafeedback


# Basic list view with using a template
class IdeaFeedbackList(ListView):
    model = IdeaFeedback
    template_name = 'ideafeedback_list.html'

    # Filter the list of choices
    queryset = query_ideafeedback()

    # Use the request user to match the items
    #def get_queryset(self):
    #    return IdeaFeedback.objects.filter(name=self.request.user.username)


# Basic detail view
class IdeaFeedbackDetail(DetailView):
    model = IdeaFeedback
    template_name = 'ideafeedback_detail.html'

    # Call the base implementation first to get a context
    def get_context_data(self, **kwargs):
        context = super(IdeaFeedbackDetail, self).get_context_data(**kwargs)
        id = context['object'].pk
        context['value_list'] = get_ideafeedback(self.request.user,id)
        return context


# Create view
class IdeaFeedbackAdd(CreateView):
    model = IdeaFeedback
    template_name = 'ideafeedback_edit.html'


# Update view
#@login_required(login_url='/login')
class IdeaFeedbackEdit(UpdateView):
    model = IdeaFeedback
    template_name = 'ideafeedback_edit.html'


# Delete view
class IdeaFeedbackDelete(DeleteView):
    model = IdeaFeedback
    success_url = reverse_lazy('ideafeedback_list')
    template_name = 'ideafeedback_delete.html'

