# srs/views_dt.py
# Idea views for basic operations


#############################################################################
# DO NOT EDIT THIS FILE
# This Code will be replaced by the code generator
#############################################################################

from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.decorators import login_required

from models import Idea
from idea import query_idea, get_idea


# Basic list view with using a template
class IdeaList(ListView):
    model = Idea
    template_name = 'idea_list.html'

    # Filter the list of choices
    queryset = query_idea()

    # Use the request user to match the items
    #def get_queryset(self):
    #    return Idea.objects.filter(name=self.request.user.username)


# Basic detail view
class IdeaDetail(DetailView):
    model = Idea
    template_name = 'idea_detail.html'

    # Call the base implementation first to get a context
    def get_context_data(self, **kwargs):
        context = super(IdeaDetail, self).get_context_data(**kwargs)
        id = context['object'].pk
        context['value_list'] = get_idea(self.request.user,id)
        return context


# Create view
class IdeaAdd(CreateView):
    model = Idea
    template_name = 'idea_edit.html'


# Update view
#@login_required(login_url='/login')
class IdeaEdit(UpdateView):
    model = Idea
    template_name = 'idea_edit.html'


# Delete view
class IdeaDelete(DeleteView):
    model = Idea
    success_url = reverse_lazy('idea_list')
    template_name = 'idea_delete.html'

