# views_dt.py
# IdeaGroup views

#############################################################################
# DO NOT EDIT THIS FILE
# This Code will be replaced by the code generator
#############################################################################

from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.decorators import login_required

from models import IdeaGroup
from ideagroup import query_ideagroup, get_ideagroup


# Basic list view with using a template
@login_required(login_url='/login')
class IdeaGroupList(ListView):
    model = IdeaGroup
    template_name = 'ideagroup_list.html'

    # Filter the list of choices
    queryset = query_ideagroup()

    # Use the request user to match the items
    #def get_queryset(self):
    #    return IdeaGroup.objects.filter(name=self.request.user.username)


# Basic detail view
@login_required(login_url='/login')
class IdeaGroupDetail(DetailView):
    model = IdeaGroup
    template_name = 'ideagroup_detail.html'

    # Call the base implementation first to get a context
    def get_context_data(self, **kwargs):
        context = super(IdeaGroupDetail, self).get_context_data(**kwargs)
        id = context['object'].pk
        context['value_list'] = get_ideagroup(self.request.user,id)
        return context


# Create view
@login_required(login_url='/login')
class IdeaGroupAdd(CreateView):
    model = IdeaGroup
    template_name = 'ideagroup_edit.html'


# Update view
@login_required(login_url='/login')
class IdeaGroupEdit(UpdateView):
    model = IdeaGroup
    template_name = 'ideagroup_edit.html'


# Delete view
@login_required(login_url='/login')
class IdeaGroupDelete(DeleteView):
    model = IdeaGroup
    success_url = reverse_lazy('ideagroup_list')
    template_name = 'ideagroup_delete.html'

