# srs/views_dt.py
# Kudo views for basic operations


#############################################################################
# DO NOT EDIT THIS FILE
# This Code will be replaced by the code generator
#############################################################################

from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.decorators import login_required

from models import Kudo
from kudo import query_kudo, get_kudo


# Basic list view with using a template
class KudoList(ListView):
    model = Kudo
    template_name = 'kudo_list.html'

    # Filter the list of choices
    queryset = query_kudo()

    # Use the request user to match the items
    #def get_queryset(self):
    #    return Kudo.objects.filter(name=self.request.user.username)


# Basic detail view
class KudoDetail(DetailView):
    model = Kudo
    template_name = 'kudo_detail.html'

    # Call the base implementation first to get a context
    def get_context_data(self, **kwargs):
        context = super(KudoDetail, self).get_context_data(**kwargs)
        id = context['object'].pk
        context['value_list'] = get_kudo(self.request.user,id)
        return context


# Create view
class KudoAdd(CreateView):
    model = Kudo
    template_name = 'kudo_edit.html'


# Update view
#@login_required(login_url='/login')
class KudoEdit(UpdateView):
    model = Kudo
    template_name = 'kudo_edit.html'


# Delete view
class KudoDelete(DeleteView):
    model = Kudo
    success_url = reverse_lazy('kudo_list')
    template_name = 'kudo_delete.html'

