# srs/views_dt.py
# Provider views for basic operations


#############################################################################
# DO NOT EDIT THIS FILE
# This Code will be replaced by the code generator
#############################################################################

from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.decorators import login_required

from models import Provider
from provider import query_provider, get_provider


# Basic list view with using a template
class ProviderList(ListView):
    model = Provider
    template_name = 'provider_list.html'

    # Filter the list of choices
    queryset = query_provider()

    # Use the request user to match the items
    #def get_queryset(self):
    #    return Provider.objects.filter(name=self.request.user.username)


# Basic detail view
class ProviderDetail(DetailView):
    model = Provider
    template_name = 'provider_detail.html'

    # Call the base implementation first to get a context
    def get_context_data(self, **kwargs):
        context = super(ProviderDetail, self).get_context_data(**kwargs)
        id = context['object'].pk
        context['value_list'] = get_provider(self.request.user,id)
        return context


# Create view
class ProviderAdd(CreateView):
    model = Provider
    template_name = 'provider_edit.html'


# Update view
#@login_required(login_url='/login')
class ProviderEdit(UpdateView):
    model = Provider
    template_name = 'provider_edit.html'


# Delete view
class ProviderDelete(DeleteView):
    model = Provider
    success_url = reverse_lazy('provider_list')
    template_name = 'provider_delete.html'

